/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Mailbox.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Mailbox(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Mailbox.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Empty" />
        <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.Material} position={[0, 0.5, 0]} rotation={[0.261, 3.6, 0]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.002']} position={[-0.203, -0.912, 0]} />
          <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.001']} position={[0.995, 0, -0.15]} rotation={[0, 0, -Math.PI / 2]} scale={0.041} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Mailbox.glb')
