/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Rocks.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'
import { MeshPhysicalMaterial } from 'three'

export function Rocks(props) {
  const { nodes, materials } = useGLTF('/Rocks.glb')
  const texture = useTexture('/Rocks.png')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock_Type1_02_mesh002.geometry} material={materials['color2.001']} position={[-5.9, -0.8, -2.945]} rotation={[-Math.PI, 0.643, -Math.PI]} />
    
    </group>
  )
}

useGLTF.preload('/Rocks.glb')
